### ISSUE TITLE
Midifile import fail

### ISSUE THREAD

**Issue by Patochun** [OmarEmaraDev/midi-parser#3]
Traceback (most recent call last):
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'AN_MIDI_STD_LOOP'", line 11, in <module>
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\nodes\midi\fileParser.py", line 50, in execute
    tracks = MidiParseFile(path)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\utils\midi.py", line 59, in MidiParseFile
    midi = MidiFile.fromFile(filemid)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 143, in fromFile
    tracks = parseTracks(memoryMap, tracksCount)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 130, in parseTracks
    return [MidiTrack.fromMemoryMap(memoryMap) for i in range(tracksCount)]
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 130, in <listcomp>
    return [MidiTrack.fromMemoryMap(memoryMap) for i in range(tracksCount)]
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 118, in fromMemoryMap
    events = parseEvents(memoryMap)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 101, in parseEvents
    event = parseEvent(memoryMap, parseState)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 87, in parseEvent
    return parseMetaEvent(deltaTime, memoryMap)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 68, in parseMetaEvent
    event = eventClass.fromMemoryMap(deltaTime, length, memoryMap)
  File "C:\Users\patoc\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\midiparser\events.py", line 118, in fromMemoryMap
    copyright = struct.unpack(f"{length}s", memoryMap.read(length))[0].decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 10: ordinal not in range(128)

**Comment by OmarEmaraDev** [comment]
Do you happened to know what the copyright text is? It is probably the Unicode Character “©” (U+00A9).

**Comment by OmarEmaraDev** [comment]
Fixed in cbe4e36.

**Comment by Patochun** [comment]
Can you merge the fix into midi branch of AN ?

**Comment by OmarEmaraDev** [comment]
It is already merged in commit 55022a6.
